import { useAuth0 } from "@auth0/auth0-react";
import Head from "next/head";

export default function Home() {
  const { user, logout } = useAuth0();

  return (
    <>
      <Head>
        <title>トップ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>トップ</h1>
        <p>{user?.name}</p>
        <button onClick={() => logout()}>ログアウト</button>
      </main>
    </>
  );
}
